// src/types/database.types.ts
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by Supabase CLI — DO NOT EDIT MANUALLY.
// Regenerate after any schema migration:
//   npx supabase gen types typescript --project-id <YOUR_PROJECT_ID> \
//     > src/types/database.types.ts
//
// This stub provides the Database generic so TypeScript compiles.
// Replace with the real generated output once your Supabase project is live.
// ─────────────────────────────────────────────────────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      // Core tables — columns inferred from 001–011 migrations
      users: {
        Row: {
          id: string;
          auth_user_id: string | null;
          full_name: string;
          email: string;
          phone: string | null;
          avatar_url: string | null;
          is_active: boolean;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'> & { id?: string };
        Update: Partial<Database['public']['Tables']['users']['Row']>;
      };
      deals: {
        Row: {
          id: string;
          deal_number: string;
          title: string | null;
          description: string | null;
          company_name: string;
          industry_id: string | null;
          website: string | null;
          country: string | null;
          employee_headcount: number | null;
          current_system: string | null;
          source_id: string | null;
          referral_source: string | null;
          owner_id: string;
          assigned_to: string | null;
          stage_id: string;
          status_id: string;
          priority_id: string | null;
          product_id: string | null;
          proposal_value: number | null;
          final_contract_value: number | null;
          contract_duration_months: number | null;
          expected_close_date: string | null;
          won_at: string | null;
          lost_at: string | null;
          next_followup_date: string | null;
          last_activity_at: string | null;
          won_reason_id: string | null;
          won_remark: string | null;
          won_by: string | null;
          lost_at_stage_id: string | null;
          loss_reason_id: string | null;
          loss_remark: string | null;
          lost_by: string | null;
          created_by: string;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_active: boolean;
          metadata: Json | null;
        };
        Insert: Partial<Database['public']['Tables']['deals']['Row']> & { company_name: string; owner_id: string; stage_id: string; status_id: string; created_by: string };
        Update: Partial<Database['public']['Tables']['deals']['Row']>;
      };
      tasks: {
        Row: {
          id: string;
          deal_id: string;
          contact_id: string | null;
          assigned_to: string | null;
          title: string;
          description: string | null;
          priority: string | null;
          status: string;
          due_date: string | null;
          completed_at: string | null;
          next_followup_date: string | null;
          is_overdue: boolean;
          is_follow_up: boolean;
          follow_up_source_type: string | null;
          follow_up_source_id: string | null;
          created_by: string;
          updated_by: string | null;
          completed_by: string | null;
          created_at: string;
          updated_at: string;
          is_active: boolean;
        };
        Insert: Partial<Database['public']['Tables']['tasks']['Row']> & { deal_id: string; title: string; created_by: string };
        Update: Partial<Database['public']['Tables']['tasks']['Row']>;
      };
      meetings: {
        Row: {
          id: string;
          deal_id: string;
          contact_id: string | null;
          assigned_to: string | null;
          meeting_type: string;
          meeting_status: string;
          title: string;
          agenda: string | null;
          location: string | null;
          meeting_url: string | null;
          participants: string[] | null;
          scheduled_at: string;
          started_at: string | null;
          ended_at: string | null;
          summary: string | null;
          outcome: string | null;
          outcome_recorded_at: string | null;
          next_followup_date: string | null;
          created_by: string;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_active: boolean;
        };
        Insert: Partial<Database['public']['Tables']['meetings']['Row']> & { deal_id: string; title: string; scheduled_at: string; created_by: string };
        Update: Partial<Database['public']['Tables']['meetings']['Row']>;
      };
      deal_contacts: {
        Row: {
          id: string;
          deal_id: string;
          role_id: string | null;
          first_name: string;
          last_name: string | null;
          full_name: string;
          designation: string | null;
          department: string | null;
          email: string | null;
          phone: string | null;
          mobile: string | null;
          linkedin_url: string | null;
          is_primary: boolean;
          notes: string | null;
          last_contacted_at: string | null;
          created_by: string;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
          is_active: boolean;
        };
        Insert: Partial<Database['public']['Tables']['deal_contacts']['Row']> & { deal_id: string; first_name: string; created_by: string };
        Update: Partial<Database['public']['Tables']['deal_contacts']['Row']>;
      };
    };
    Views: {
      // Views from 011_views_and_reporting.sql
      v_dashboard_kpis: { Row: Record<string, unknown> };
      v_pipeline_by_stage: { Row: Record<string, unknown> };
      v_overdue_tasks_summary: { Row: Record<string, unknown> };
      v_upcoming_followups_summary: { Row: Record<string, unknown> };
      v_deals_closing_this_month: { Row: Record<string, unknown> };
      v_followup_dashboard: { Row: Record<string, unknown> };
      v_deal_timeline_display: { Row: Record<string, unknown> };
      v_pipeline_list: { Row: Record<string, unknown> };
    };
    Functions: {
      rpc_change_deal_stage: {
        Args: { p_deal_id: string; p_new_stage_id: string; p_remark: string };
        Returns: void;
      };
      rpc_reassign_deal: {
        Args: { p_deal_id: string; p_new_assignee_id: string; p_remark: string };
        Returns: void;
      };
      get_current_user_role: { Args: Record<never, never>; Returns: string };
      has_permission: { Args: { permission_name: string }; Returns: boolean };
    };
    Enums: Record<never, never>;
  };
};
